import { Tool } from '../types';

export const TOOLS: Tool[] = [
  {
    id: 'compress-image',
    name: 'Compress Image',
    title: 'Compress Image Online',
    description: 'Reduce image file size without losing quality. Perfect for web optimization.',
    icon: 'Minimize2',
    slug: 'compress-image',
    category: 'optimize',
    isNew: true,
    seo: {
      title: 'Free Online Image Compressor - Reduce Image Size Without Quality Loss',
      description: 'Compress JPG, PNG, SVG, and GIF images online for free. Reduce file size by up to 90% while maintaining high quality. No upload required, 100% secure.',
      keywords: ['image compressor', 'reduce image size', 'compress jpg', 'compress png', 'online image optimizer'],
    },
    features: [
      'Fast client-side processing',
      'No file upload (privacy first)',
      'Adjustable quality levels',
      'Supports JPG, PNG, WebP',
    ],
    benefits: [
      'Improve website loading speed',
      'Save storage space',
      'Better SEO rankings',
    ],
    useCases: [
      'Web developers optimizing assets',
      'Bloggers uploading images to CMS',
      'Social media managers',
    ],
    faqs: [
      {
        question: 'Is this image compressor free?',
        answer: 'Yes, Sohelix Image Compressor is 100% free to use with no hidden costs or limits.',
      },
      {
        question: 'Does it affect image quality?',
        answer: 'Our tool uses advanced algorithms to reduce file size while maintaining the best possible visual quality.',
      },
      {
        question: 'Are my images safe?',
        answer: 'Absolutely. All processing happens in your browser. Your images are never uploaded to our servers.',
      },
    ],
    longContent: 'Optimizing images is crucial for modern web performance. Large image files can slow down your website, leading to poor user experience and lower search engine rankings. Sohelix provides a professional-grade compression tool that works entirely in your browser. This means your data stays private and the processing is lightning fast. Whether you are a developer looking to shave off kilobytes from your production assets or a casual user trying to save space on your phone, our tool is designed to deliver the best results with zero friction.',
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    title: 'Resize Image Online',
    description: 'Change image dimensions by pixels or percentage easily.',
    icon: 'Maximize2',
    slug: 'resize-image',
    category: 'edit',
    seo: {
      title: 'Free Online Image Resizer - Change Image Dimensions Fast',
      description: 'Resize JPG, PNG, and WebP images online for free. Change width and height in pixels or percentage. Maintain aspect ratio and high quality.',
      keywords: ['image resizer', 'resize image online', 'change image dimensions', 'resize jpg', 'resize png'],
    },
    features: [
      'Resize by pixels or percentage',
      'Maintain aspect ratio lock',
      'Bulk resizing support',
      'Instant preview',
    ],
    benefits: [
      'Perfect for social media profiles',
      'Standardize image sizes for galleries',
      'Quick adjustments for documents',
    ],
    useCases: [
      'Creating thumbnails',
      'Fitting images into specific UI layouts',
      'Preparing photos for printing',
    ],
    faqs: [
      {
        question: 'Can I resize multiple images at once?',
        answer: 'Yes, you can upload and resize multiple images simultaneously.',
      },
      {
        question: 'Will resizing make my image blurry?',
        answer: 'Upscaling an image beyond its original size may cause blurriness, but downscaling maintains high clarity.',
      },
    ],
    longContent: 'Resizing images is a common task for anyone working with digital media. Whether you need a specific width for a blog post or a square aspect ratio for Instagram, Sohelix makes it simple. Our resizer allows you to input exact pixel values or use a percentage slider for quick adjustments. With the "Maintain Aspect Ratio" feature, you never have to worry about stretching or distorting your photos. Everything happens locally on your device, ensuring maximum speed and security.',
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    title: 'Crop Image Online',
    description: 'Remove unwanted parts of an image with precision.',
    icon: 'Crop',
    slug: 'crop-image',
    category: 'edit',
    seo: {
      title: 'Free Online Image Cropper - Crop JPG, PNG, WebP Easily',
      description: 'Crop your images online for free. Use preset aspect ratios or free-form selection. High precision cropping with instant download.',
      keywords: ['image cropper', 'crop image online', 'remove image borders', 'crop photo'],
    },
    features: [
      'Preset aspect ratios (1:1, 4:3, 16:9)',
      'Free-form selection',
      'Rotation while cropping',
      'High-res output',
    ],
    benefits: [
      'Focus on the subject',
      'Remove distracting backgrounds',
      'Create perfect profile pictures',
    ],
    useCases: [
      'Photography editing',
      'E-commerce product photos',
      'Personal photo archiving',
    ],
    faqs: [
      {
        question: 'Is the cropping tool precise?',
        answer: 'Yes, you can drag the corners to select the exact area you want to keep.',
      },
    ],
    longContent: 'Sometimes a photo is perfect except for a few distracting elements at the edges. Our cropping tool gives you the control to frame your images exactly how you want them. With support for common aspect ratios, you can quickly prepare images for any platform. Like all Sohelix tools, the cropper runs entirely in your browser, keeping your private photos private.',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    title: 'Convert JPG to PNG',
    description: 'Convert JPG images to PNG format with transparency support.',
    icon: 'FileImage',
    slug: 'jpg-to-png',
    category: 'convert',
    seo: {
      title: 'Convert JPG to PNG Online - Free & High Quality',
      description: 'Convert your JPG files to PNG format online for free. High quality conversion, no file size limits, and 100% secure processing.',
      keywords: ['jpg to png', 'convert jpg to png', 'online image converter', 'jpg to png free'],
    },
    features: [
      'High fidelity conversion',
      'Batch processing',
      'No quality loss',
      'Instant download',
    ],
    benefits: [
      'Better compatibility for some apps',
      'Lossless format conversion',
      'Easy to use',
    ],
    useCases: [
      'Developers needing PNG assets',
      'Users converting photos for specific software',
    ],
    faqs: [
      {
        question: 'Will the file size increase?',
        answer: 'PNG is a lossless format, so the file size might be larger than the original JPG.',
      },
    ],
    longContent: 'Converting between image formats is a fundamental need for designers and developers. JPG is great for photos, but PNG is often required for logos or images that need transparency. Sohelix provides a fast, reliable way to convert your files without ever sending them to a server.',
  },
  {
    id: 'webp-converter',
    name: 'WebP Converter',
    title: 'Convert to WebP',
    description: 'Convert any image to WebP for superior web performance.',
    icon: 'Zap',
    slug: 'webp-converter',
    category: 'convert',
    seo: {
      title: 'Free WebP Converter - Convert JPG/PNG to WebP Online',
      description: 'Convert your images to WebP format for faster website loading. Free online converter for JPG, PNG, and more.',
      keywords: ['webp converter', 'convert to webp', 'jpg to webp', 'png to webp', 'optimize for web'],
    },
    features: [
      'Superior compression',
      'Supports transparency',
      'Modern web standard',
    ],
    benefits: [
      'Faster page loads',
      'Better Core Web Vitals',
      'Smaller file sizes',
    ],
    useCases: [
      'SEO optimization',
      'Mobile app assets',
    ],
    faqs: [],
    longContent: 'WebP is the modern image format for the web. It provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster.',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    title: 'Convert PNG to JPG',
    description: 'Convert PNG images to JPG format quickly.',
    icon: 'FileImage',
    slug: 'png-to-jpg',
    category: 'convert',
    seo: {
      title: 'Convert PNG to JPG Online - Free & Fast',
      description: 'Convert your PNG files to JPG format online for free. High quality conversion with adjustable quality settings.',
      keywords: ['png to jpg', 'convert png to jpg', 'online image converter'],
    },
    features: ['Fast conversion', 'Quality control', 'Batch support'],
    benefits: ['Reduce file size', 'Better compatibility'],
    useCases: ['Web optimization', 'Email attachments'],
    faqs: [],
    longContent: 'PNG files are great for transparency, but they can be large. Converting them to JPG is a great way to save space when transparency is not needed.',
  },
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    title: 'Convert Image to Base64',
    description: 'Encode your images into Base64 strings for CSS or HTML.',
    icon: 'Code',
    slug: 'image-to-base64',
    category: 'misc',
    seo: {
      title: 'Image to Base64 Converter - Encode Images Online',
      description: 'Convert images to Base64 strings online. Perfect for embedding images directly into HTML or CSS files.',
      keywords: ['image to base64', 'base64 encoder', 'data uri generator'],
    },
    features: ['Instant encoding', 'Copy to clipboard', 'Data URI support'],
    benefits: ['Reduce HTTP requests', 'Embed images in code'],
    useCases: ['Web development', 'Email templates'],
    faqs: [],
    longContent: 'Base64 encoding allows you to embed image data directly into your code. This can reduce the number of HTTP requests your website makes, potentially improving load times for small assets.',
  },
  {
    id: 'image-watermark',
    name: 'Image Watermark',
    title: 'Add Watermark to Image',
    description: 'Protect your images with text or image watermarks.',
    icon: 'Stamp',
    slug: 'image-watermark',
    category: 'edit',
    seo: {
      title: 'Add Watermark to Image Online - Free & Secure',
      description: 'Protect your photos by adding text or image watermarks online. Customize position, opacity, and size.',
      keywords: ['add watermark', 'watermark image', 'protect photos', 'online watermark tool'],
    },
    features: ['Text & Image watermarks', 'Custom positioning', 'Opacity control'],
    benefits: ['Protect copyright', 'Brand your images'],
    useCases: ['Photographers', 'Content creators'],
    faqs: [],
    longContent: 'Watermarking is essential for protecting your creative work online. Sohelix allows you to add custom text or your own logo as a watermark to any image, all within your browser.',
  },
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    title: 'Online Meme Generator',
    description: 'Create funny memes with custom text and images.',
    icon: 'Smile',
    slug: 'meme-generator',
    category: 'edit',
    seo: {
      title: 'Free Online Meme Generator - Create Memes Instantly',
      description: 'Create your own memes online for free. Upload your images and add custom text. Fast, fun, and easy to use.',
      keywords: ['meme generator', 'make a meme', 'online meme maker', 'custom memes'],
    },
    features: ['Custom text', 'Drag & drop text', 'Font options'],
    benefits: ['Quick creation', 'Shareable content'],
    useCases: ['Social media', 'Entertainment'],
    faqs: [],
    longContent: 'Memes are the language of the internet. Our meme generator makes it easy to turn any image into a viral sensation. Add top and bottom text, adjust fonts, and download your creation in seconds.',
  },
  {
    id: 'image-rotate',
    name: 'Image Rotate',
    title: 'Rotate Image Online',
    description: 'Rotate your images clockwise or counter-clockwise.',
    icon: 'RotateCw',
    slug: 'image-rotate',
    category: 'edit',
    seo: {
      title: 'Rotate Image Online - Free & Instant',
      description: 'Rotate your images 90, 180, or 270 degrees online. Free tool for JPG, PNG, and WebP.',
      keywords: ['rotate image', 'turn image', 'image rotation tool'],
    },
    features: ['90° increments', 'Custom rotation', 'Instant preview'],
    benefits: ['Fix orientation', 'Creative adjustments'],
    useCases: ['Fixing mobile photos', 'Design work'],
    faqs: [],
    longContent: 'Sometimes images come out sideways or upside down. Our rotation tool lets you fix the orientation of your photos quickly and easily.',
  },
  {
    id: 'blur-image',
    name: 'Blur Image',
    title: 'Blur Image Online',
    description: 'Apply blur effects to your images or specific areas.',
    icon: 'Droplets',
    slug: 'blur-image',
    category: 'edit',
    seo: {
      title: 'Blur Image Online - Free Blur Effect Tool',
      description: 'Apply professional blur effects to your images online. Adjust blur intensity and focus.',
      keywords: ['blur image', 'image blur tool', 'soften photo'],
    },
    features: ['Adjustable intensity', 'Gaussian blur', 'Fast processing'],
    benefits: ['Hide sensitive info', 'Creative depth of field'],
    useCases: ['Privacy protection', 'Design aesthetics'],
    faqs: [],
    longContent: 'Blurring can be used for both privacy and artistic effect. Whether you need to hide a face or create a soft background for text, our blur tool is here to help.',
  }
];
